### ISSUE TITLE
model forecast doesn't scale

### ISSUE THREAD

**Issue by jswhit** [jswhit/replay_scripts#13]
appears that the ATM component is spending a lot of time waiting (for something), and this latency is preventing the workflow from scaling.

**Comment by jswhit** [comment]
@pjpegion found that "based on the timings, the ocean is idle 73% of the time, and the atmosphere is idle 66% of the time.  I am not sure how to get timings for the coupler and the ice model"

whereas for P8 "the atmosphere model is idle 19% of the time, and the ocean is idle 55% of the time"

From Jessica:

The P8 runs are not perfectly balanced, but there was some effort made.  I stopped mid-way through since it met our wallclock restrictions and we knew new features coming in would require completely redoing the efforts. Some of these runs are documented [here](https://docs.google.com/spreadsheets/d/16_94Evh2UnTGc_wNJxZOfR3IRrH_vq5MlpmRqVGQmCY/edit?usp=sharing) in case that's of any help (I did more runs than that but can't find them at this moment, probably didn't make it to a spreadsheet).

The way I load balance things is to use the ESMF profiling (see instructions [here](https://github.com/ufs-community/ufs-weather-model/wiki/Advanced-Topics-for-developers/#profiling-timing-across-components)).  Jun has also been leading a group who's been looking into road blocks for scalability so she might have additional insight for you as well.  Based on some of those conversations, it might be that you're waiting on the ocean model to write restarts?  You might need another write group if you're writing more often than what we did in the prototypes (every 6 hours).  If you get a  ESMF_Profile.summary  file from one of your runs I'd be happy to take a look at it and see if there's something I'd recommend for changes.  There are other tools that give even more detailed looks that can be used to see things that you don't see in the average/total timings given in the ESMF profiler, but I'd start with just getting the summary first.

**Comment by jswhit** [comment]
the culprit appears to be ocean restart writes.  PR #12 reduces the number of restarts written, which results in a 50% speedup

**Comment by pjpegion** [comment]
I also noticed that we are using compression while writing the restarts, I think this is the difference between the 3 minutes per write we are seeing compared to the 1-minute per write data-atmosphere is getting.

**Comment by jswhit** [comment]
I tried turning off compression and it had no discernible impact on runtime

**Comment by pjpegion** [comment]
hmm, it had a big impact on my test.  1700s->1000s

**Comment by jswhit** [comment]
NVM - i didn't actually turn it off.  Will rerun

**Comment by jswhit** [comment]
takes about a minute per file to rewrite the MOM6 restart files with compression using nccopy -k 4 -d 1 (but all three files can be done in parallel).  Files are about half the size after compressoin.

**Comment by pjpegion** [comment]
> I do see a speedup turning off compression - saves another couple hundred seconds. Odd that the ATM restart files are ignoring the compression settings in mpp_io_nml - I know that didn't used to be the case (with the atmosphere only model at least).

I think this because the atmosphere is now using fms2_io,  there may be a namelist block we can add for that.
